# Generated by Django 4.2.4 on 2024-01-24 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('supplier', models.CharField(max_length=255)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('initial_quantity', models.PositiveIntegerField()),
                ('current_quantity', models.PositiveIntegerField()),
                ('min_threshold', models.PositiveIntegerField(default=10)),
            ],
        ),
    ]
